version: '3.8'

services:

    frontend:
        image: frontend

    backend:
        image: backend
        environment:
          - REDIS_HOST=redis
          - POSTGRES_HOST=db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - POSTGRES_DATABASE=dbname

    redis:
        image: redis

    db:
        image: postgres
        environment:
           - POSTGRES_USER=user
           - POSTGRES_PASSWORD=password
           - POSTGRES_DB=dbname

    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      container_name: nginx
