version: '3.8'

services:

    frontend:
        image: frontend
        ports:
          - 5000:5000
        restart: unless-stopped

    backend:
        image: backend
        ports:
          - 8080:8080
        environment:
          - REDIS_HOST=redis
          - POSTGRES_HOST=db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - POSTGRES_DATABASE=dbname
        restart: unless-stopped

    redis:
        image: redis
        volumes:
          - ./redis:/data
        restart: unless-stopped

    db:
        image: postgres
        volumes:
          - ./database:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=dbname
        restart: unless-stopped
