FROM ubuntu:18.04

EXPOSE 5000

ENV REACT_APP_BACKEND_URL=http://localhost:80/api/

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs

COPY example-frontend frontend
WORKDIR /frontend

RUN npm install
RUN npm run build
RUN npm install -g serve

CMD serve -s -l 5000 build

